"""empty message

Revision ID: 911f49e0ef92
Revises: cce0d9db47a7
Create Date: 2025-05-20 16:33:32.875749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '911f49e0ef92'
down_revision = 'cce0d9db47a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('train_positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('train_no', sa.String(length=10), nullable=False),
    sa.Column('subway_id', sa.String(length=10), nullable=False),
    sa.Column('statn_nm', sa.String(length=50), nullable=False),
    sa.Column('statn_id', sa.String(length=20), nullable=True),
    sa.Column('statn_tnm', sa.String(length=50), nullable=True),
    sa.Column('recptn_dt', sa.DateTime(), nullable=True),
    sa.Column('train_sttus', sa.Integer(), nullable=True),
    sa.Column('updn_line', sa.Integer(), nullable=True),
    sa.Column('direct_at', sa.Integer(), nullable=True),
    sa.Column('lstcar_at', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_train_positions'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('train_positions')
    # ### end Alembic commands ###
